name: Docker Build Image

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ''

jobs:
  docker:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >> "${GITHUB_ENV}"
      - name: extract version
        id: extract_version
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest